= Starter Upper

Starter Upper automates set up of git and hosting services so that students and
faculty may use http://db.grinnell.edu/sigcse/sigcse2013/Program/viewAcceptedProposal.pdf?sessionType=paper&sessionNumber=257[git on the cloud in the classroom].
It configures everyone's full name, email, and SSH keys for git and project
hosts, assists in setting up project hosting accounts, and
creates a private repository shared only with the instructor.
For instructors, Starter Upper collects the class roster to fetch student work.

== Step 1. Install Git
Download and install git for your platform.

[cols="1a,2a"]
|===
|*Download*
|*Installation Notes*

|https://git-scm.com/download/win[Git for Windows]
|Stick with the default options and click `Next` until finished.

|http://git-scm.com/download/mac[Git for Mac OS X]
|Got an error? Try:

* Apple menu -> System Preferences... -> Security & Privacy -> Open Anyway.
* Otherwise, try: Command Space (Spotlight Search) -> Terminal and type `git` and follow instructions to install git.

|http://git-scm.com/download/linux[Git for Linux]
|Use `sudo` with your package manager.

|===

== Step 2. Faculty instructions

. Copy/paste this command into Git Bash or Terminal to clone this repository:
+
----
curl https://raw.githubusercontent.com/lawrancej/starterupper/master/main.sh | bash
----

. Copy `main.sh` into your course repository
. Change as necessary for your course

== Step 3. Student instructions

Students will copy/paste a command similar to this into Git Bash or Terminal
(substitute `YOUR-NAME-HERE` and `COURSE-REPOSITORY` as appropriate for students):

----
curl https://raw.githubusercontent.com/YOUR-NAME-HERE/COURSE-REPOSITORY/master/main.sh | bash
----

== References

* https://git.wiki.kernel.org/index.php/GitHosting[Git hosts]
